server:
  port: 8085

spring:
  application:
    name: brazz-nossel

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IDP_PROVIDER_PROTOCOL}://${IDP_PROVIDER_HOST}/realms/${IDP_PROVIDER_REALM}/protocol/openid-connect/certs
